version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: webalize-db
    env_file:
      - test.env
    environment:
      - POSTGRES_USER=payload_user
      - POSTGRES_PASSWORD=payload_pass
      - POSTGRES_DB=payload_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
